#w repliacationController jest apiVersion: v1
apiVersion: apps/v1 
kind: Deployment
metadata:
 name: myapp-deployment
 namespace: dev
 labels:
  anyLabel: anyVal
spec:
#ponizej piszemy template poda, jak w pod.xml
 template:
  metadata:
   name: myapp-pod
   labels:
    innerLabel: blah
  spec:
   containers:
   - name: nginx-container
     image: nginx
 replicas: 3
#ReplicaSet wymaga dodatkowo 'selector:'
 selector:
  matchLabels:
   innerLabel: blah
