apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deployment
  labels:
    app: my-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
        - name: spring-app
          image: spring-app:v7-env
          command: ["sh", "-c", "java -jar app-0.0.1-SNAPSHOT.jar --cmdLineArgument=nadpisanie_args"]
          ports:
            - containerPort: 8080
          envFrom:
           - configMapRef:
              name: spring-app-configmap
